// Prisma-backed implementation of `ReportingRepository`
// (src/modules/reporting/repository.ts).
//
// ============================================================================
// READ THIS BEFORE TOUCHING THIS FILE
// ============================================================================
// This file imports `@prisma/client`, whose TypeScript types are GENERATED by
// `npx prisma generate` from `prisma/schema.prisma`. That command cannot succeed in
// this dev container: `prisma generate`'s internal DMMF-computation step needs the
// native query-engine binary from `binaries.prisma.sh`, which this container's network
// policy blocks — confirmed even with the JS/WASM schema-engine mode already configured
// in `prisma.config.ts` (that gets the Schema Engine itself working, but the CLI's DMMF
// bootstrap for ANY command still needs the native query engine regardless).
//
// Consequences, both deliberate:
//   1. `npx tsc --noEmit`, `npx eslint .`, and `npx next build` will all fail on this
//      file today with "module '@prisma/client' has no exported member ..." — NOT
//      because the code below is wrong, but because the types it imports don't exist
//      on disk yet. This file is listed in `tsconfig.json`'s `exclude` array and in
//      `eslint.config.mjs`'s ignores for exactly this reason.
//   2. This is real, finished code — written exactly as it would be in a normal,
//      working Prisma project, against the actual field names/types/relations in
//      `prisma/schema.prisma`. It is NOT a stub. Once `prisma generate` has been run
//      somewhere with real network access (Vercel's build, or a developer's own
//      machine), this file typechecks and runs as-is — no further edits needed.
//   3. This file is NOT wired into `src/server/container.ts` yet. That composition-root
//      swap-over is intentionally deferred to whenever `prisma generate` can actually
//      run — see that file's own header comment.
// ============================================================================
//
// Mapping notes:
// - `reporting` owns no entity of its own (reporting-business-rules.md's header note,
//   repository.ts's own header comment) — it only ever counts rows on the
//   (booking-owned) `Appointment` table, so there is no domain-type row-mapping function
//   here at all, unlike every other module's `prisma/repository.ts` — `countAppointmentsInRange`
//   returns plain aggregate numbers straight from Prisma's `count`, not mapped rows.
// - BR-REPORT-2 — `totalAppointments` counts every `Appointment` in `range` regardless of
//   `status` (including `Cancelled` — Q6=B, types.ts's own doc comment), so its `count`
//   call carries no `status` filter at all.
// - BR-REPORT-3 — `noShowCount` is the same range filter plus `status: "NoShow"`.
// - Range filtering is half-open `[start, end)` — `slotStart >= range.start && slotStart
//   < range.end` — matching `DateRange`'s own doc comment in this module's types.ts
//   ("Half-open `[start, end)` calendar range") and `tests/fakes/reporting.fake.ts`'s
//   fake implementation, which filters the exact same way.
// - The two counts are independent, non-overlapping-in-meaning queries (one is a subset
//   of the other by `status`, not a different `range`), so they're issued as two
//   concurrent `prisma.appointment.count` calls via `Promise.all` rather than one query
//   with client-side post-filtering — simpler than a single `groupBy` for just two
//   numbers, and avoids re-deriving `noShowCount` from a larger result set in memory.

import { PrismaClient } from "@prisma/client";
import type { AppointmentCountsForRange, ReportingRepository } from "../repository";
import type { DateRange } from "../types";

export function createPrismaReportingRepository(prisma: PrismaClient): ReportingRepository {
  return {
    async countAppointmentsInRange(range: DateRange): Promise<AppointmentCountsForRange> {
      const [totalAppointments, noShowCount] = await Promise.all([
        prisma.appointment.count({
          where: { slotStart: { gte: range.start, lt: range.end } }, // BR-REPORT-2 — every status
        }),
        prisma.appointment.count({
          where: { slotStart: { gte: range.start, lt: range.end }, status: "NoShow" }, // BR-REPORT-3
        }),
      ]);
      return { totalAppointments, noShowCount };
    },
  };
}
