// Prisma-backed implementation of `NotificationRepository`
// (src/modules/notification/repository.ts).
//
// ============================================================================
// READ THIS BEFORE TOUCHING THIS FILE
// ============================================================================
// This file imports `@prisma/client`, whose TypeScript types are GENERATED by
// `npx prisma generate` from `prisma/schema.prisma`. That command cannot succeed in
// this dev container: `prisma generate`'s internal DMMF-computation step needs the
// native query-engine binary from `binaries.prisma.sh`, which this container's network
// policy blocks — confirmed even with the JS/WASM schema-engine mode already configured
// in `prisma.config.ts` (that gets the Schema Engine itself working, but the CLI's DMMF
// bootstrap for ANY command still needs the native query engine regardless).
//
// Consequences, both deliberate:
//   1. `npx tsc --noEmit`, `npx eslint .`, and `npx next build` will all fail on this
//      file today with "module '@prisma/client' has no exported member ..." — NOT
//      because the code below is wrong, but because the types it imports don't exist
//      on disk yet. This file is listed in `tsconfig.json`'s `exclude` array and in
//      `eslint.config.mjs`'s ignores for exactly this reason.
//   2. This is real, finished code — written exactly as it would be in a normal,
//      working Prisma project, against the actual field names/types/relations in
//      `prisma/schema.prisma`. It is NOT a stub. Once `prisma generate` has been run
//      somewhere with real network access (Vercel's build, or a developer's own
//      machine), this file typechecks and runs as-is — no further edits needed.
//   3. This file is NOT wired into `src/server/container.ts` yet. That composition-root
//      swap-over is intentionally deferred to whenever `prisma generate` can actually
//      run — see that file's own header comment.
// ============================================================================
//
// Mapping notes:
// - `ScheduledReminder.status` is a Prisma enum (`ReminderStatus`) whose members are
//   string-identical to this module's own `ReminderStatus` union (types.ts) — assigned
//   with a type-level cast, the same pattern already established by `auth`'s
//   `AuthIdentity.role`/`customer`'s `Pet.size`/`booking`'s `AppointmentStatus`.
// - `findDueReminders` (Flow 3) needs each due reminder paired with its FULL
//   `AppointmentWithLineItems` (`DueReminder`, repository.ts) — a single query with a
//   nested `include: { appointment: { include: { lineItems: true } } }` gets both in one
//   round trip. Mapping the nested `appointment` row onto `AppointmentWithLineItems`
//   duplicates `booking/prisma/repository.ts`'s own `mapAppointment` logic (field-for-
//   field, same casts) rather than importing it — this module already imports
//   `booking`'s real exported TYPE (`AppointmentWithLineItems`, per this module's own
//   established "reuse booking's real type directly" pattern, see types.ts's header
//   comment), but not booking's PRISMA repository module, to keep each module's `prisma/`
//   implementation independently self-contained (no cross-module runtime dependency
//   between two `prisma/` folders that `container.ts` will eventually wire up
//   separately). A local, private `mapAppointmentWithLineItems` below is the small,
//   deliberate duplication that avoids that coupling.
// - `markAppointmentNotificationFailed` (BR-NOTIF-4) is the one place this module writes
//   onto `booking`-owned `Appointment` state directly — same "leaf/dependency component
//   writes a specific flag onto the hub entity" pattern `availability`'s
//   `setFlaggedForReview`-equivalent write already uses (see this file's own
//   repository.ts doc comment). A plain `update` — this module never resets the flag
//   back to `false` (no retry/resend flow exists in v1, NFR Design's Resilience
//   Patterns), so no conditional logic is needed here.
// - `findPendingReminderByAppointmentId` uses `findFirst` (not `findUnique` — there is no
//   uniqueness constraint enforcing "at most one Pending reminder per appointment" at the
//   schema level, only as an invariant this module's own business logic maintains, per
//   schema.prisma's `ScheduledReminder` model comment) ordered by `id` for a deterministic
//   pick in the unexpected case more than one `Pending` row exists for the same
//   appointment.

import {
  PrismaClient,
  type Appointment as PrismaAppointment,
  type AppointmentLineItem as PrismaAppointmentLineItem,
  type ScheduledReminder as PrismaScheduledReminder,
} from "@prisma/client";
import type { AppointmentLineItem, AppointmentStatus, AppointmentWithLineItems, BookingActor } from "@/modules/booking";
import type { CreateScheduledReminderInput, DueReminder, NotificationRepository } from "../repository";
import type { ReminderStatus, ScheduledReminder } from "../types";

function mapReminder(row: PrismaScheduledReminder): ScheduledReminder {
  return {
    id: row.id,
    appointmentId: row.appointmentId,
    sendAt: row.sendAt,
    status: row.status as ReminderStatus,
  };
}

function mapLineItem(row: PrismaAppointmentLineItem): AppointmentLineItem {
  return {
    id: row.id,
    appointmentId: row.appointmentId,
    petId: row.petId,
    serviceId: row.serviceId,
    priceSnapshot: Number(row.priceSnapshot),
    durationSnapshotMinutes: row.durationSnapshotMinutes,
  };
}

/** See the file-header mapping note on why this duplicates `booking/prisma/repository.ts`'s own `mapAppointment` rather than importing it. */
function mapAppointmentWithLineItems(row: PrismaAppointment & { lineItems: PrismaAppointmentLineItem[] }): AppointmentWithLineItems {
  return {
    id: row.id,
    bookingReference: row.bookingReference,
    ownerId: row.ownerId,
    groomerId: row.groomerId,
    slotStart: row.slotStart,
    slotEnd: row.slotEnd,
    status: row.status as AppointmentStatus,
    createdBy: row.createdBy as BookingActor,
    isOverride: row.isOverride,
    hasConflict: row.hasConflict,
    flaggedForReview: row.flaggedForReview,
    notificationFailed: row.notificationFailed,
    visitNotes: row.visitNotes,
    cancelledAt: row.cancelledAt,
    cancelledBy: row.cancelledBy as BookingActor | null,
    createdAt: row.createdAt,
    lineItems: row.lineItems.map(mapLineItem),
  };
}

export function createPrismaNotificationRepository(prisma: PrismaClient): NotificationRepository {
  return {
    async createScheduledReminder(input: CreateScheduledReminderInput): Promise<ScheduledReminder> {
      const row = await prisma.scheduledReminder.create({
        data: {
          appointmentId: input.appointmentId,
          sendAt: input.sendAt,
          status: "Pending",
        },
      });
      return mapReminder(row);
    },

    async findPendingReminderByAppointmentId(appointmentId: string): Promise<ScheduledReminder | null> {
      const row = await prisma.scheduledReminder.findFirst({
        where: { appointmentId, status: "Pending" },
        orderBy: { id: "asc" },
      });
      return row ? mapReminder(row) : null;
    },

    async updateReminderStatus(reminderId: string, status: ScheduledReminder["status"]): Promise<void> {
      await prisma.scheduledReminder.update({
        where: { id: reminderId },
        data: { status },
      });
    },

    async findDueReminders(now: Date): Promise<DueReminder[]> {
      const rows = await prisma.scheduledReminder.findMany({
        where: {
          status: "Pending",
          sendAt: { lte: now },
        },
        include: { appointment: { include: { lineItems: true } } },
      });
      return rows.map((row) => ({
        reminder: mapReminder(row),
        appointment: mapAppointmentWithLineItems(row.appointment),
      }));
    },

    async markAppointmentNotificationFailed(appointmentId: string): Promise<void> {
      await prisma.appointment.update({
        where: { id: appointmentId },
        data: { notificationFailed: true },
      });
    },
  };
}
