// Appointment id pre-allocation.
//
// JUDGMENT CALL: prisma/schema.prisma gives `Appointment.id` a `@default(cuid())` — normally
// generated by the database/Prisma at insert time. But `availability.claimSlot(slot,
// appointmentId)` needs an id to correlate/exclude-self with BEFORE the Appointment row is
// ever written (Flow 1 calls `claimSlot` at step 5, `createAppointment` only at step 6) —
// component-methods.md's own signature already implies the caller knows the id upfront.
// So `booking` pre-generates the id client-side and passes it explicitly into
// `repository.createAppointment`'s input; Prisma accepts an explicit `id` on `create()`
// just as readily as it applies the `@default` when one is omitted, so this needs no
// schema change. `randomUUID()` (Node's built-in, no new dependency) is used rather than
// re-implementing cuid's algorithm — both are opaque, collision-resistant string ids, and
// nothing in any business rule depends on the id's specific format (unlike
// `bookingReference`, whose shape BR-BOOK-8 does pin down).

import { randomUUID } from "node:crypto";

export function generateAppointmentId(): string {
  return randomUUID();
}
