// booking module data-access contract — pure interface, no implementation. Business
// logic (service.ts) depends only on this abstraction, never on Prisma directly. A
// Prisma-backed implementation is wired in during Phase F, Step 17 — including the
// price/duration snapshot write nfr-design-patterns.md and BR-CAT-4 call for, which
// happens as part of `createAppointment`'s line-item insert.

import type { Groomer } from "@/modules/customer";
import type { AppointmentStatus, AppointmentWithLineItems, BookingActor, DateRange } from "./types";

export interface CreateAppointmentLineItemInput {
  petId: string;
  serviceId: string;
  priceSnapshot: number;
  durationSnapshotMinutes: number;
}

export interface CreateAppointmentInput {
  /** Pre-generated by `booking` (see id.ts) — see that file's header comment for why. */
  id: string;
  bookingReference: string;
  ownerId: string;
  groomerId: string;
  slotStart: Date;
  slotEnd: Date;
  status: "Booked";
  createdBy: BookingActor;
  isOverride: boolean;
  hasConflict: boolean;
  visitNotes: string | null;
  lineItems: CreateAppointmentLineItemInput[];
}

export interface UpdateStatusInput {
  status: AppointmentStatus;
  cancelledAt?: Date | null;
  cancelledBy?: BookingActor | null;
}

export interface BookingRepository {
  /** FR-2 — v1 has exactly one Groomer; appointments auto-assign to it. */
  findDefaultGroomer(): Promise<Groomer | null>;

  /**
   * Throws `BookingReferenceCollisionError` (./errors) on a `bookingReference`
   * unique-constraint violation (BR-BOOK-8) — service.ts catches it, generates a fresh
   * reference, and retries. Writes the line items' price/duration snapshots atomically
   * with the Appointment row (BR-CAT-4) — the values are already computed by the time
   * this is called, this method just persists them.
   */
  createAppointment(input: CreateAppointmentInput): Promise<AppointmentWithLineItems>;

  findAppointmentById(appointmentId: string): Promise<AppointmentWithLineItems | null>;
  findAppointmentByReference(bookingReference: string): Promise<AppointmentWithLineItems | null>;

  /** BR-BOOK-6/BR-BOOK-2b transitions — cancel, and the auto-complete-then-no-show exception. */
  updateStatus(appointmentId: string, fields: UpdateStatusInput): Promise<AppointmentWithLineItems>;

  /** BR-BOOK-3 — reschedule: same id/bookingReference, only the slot moves. */
  updateSlot(appointmentId: string, fields: { slotStart: Date; slotEnd: Date }): Promise<AppointmentWithLineItems>;

  /** BR-BOOK-7 — editable directly on the appointment, independent of any pet's permanent notes. */
  updateVisitNotes(appointmentId: string, visitNotes: string | null): Promise<AppointmentWithLineItems>;

  /** RC-3 "my bookings" — every Appointment (any status, upcoming and past) for this Owner. */
  listByOwner(ownerId: string): Promise<AppointmentWithLineItems[]>;

  /** SO-1 admin calendar — every Appointment (any status, any owner) whose slot falls in range. */
  listByDateRange(range: DateRange): Promise<AppointmentWithLineItems[]>;

  /**
   * BR-AVAIL-9's flagging mechanism, which that rule explicitly delegates to `booking`
   * (see availability's `SetWorkingHoursResult`/`AddTimeOffResult` doc comments) — sets
   * `Appointment.flaggedForReview` on the given ids. A no-op for an empty array.
   */
  setFlaggedForReview(appointmentIds: string[], flagged: boolean): Promise<void>;
}
