// Prisma-backed implementation of `AuthRepository` (src/modules/auth/repository.ts).
//
// ============================================================================
// READ THIS BEFORE TOUCHING THIS FILE
// ============================================================================
// This file imports `@prisma/client`, whose TypeScript types are GENERATED by
// `npx prisma generate` from `prisma/schema.prisma`. That command cannot succeed in
// this dev container: `prisma generate`'s internal DMMF-computation step needs the
// native query-engine binary from `binaries.prisma.sh`, which this container's network
// policy blocks — confirmed even with the JS/WASM schema-engine mode already configured
// in `prisma.config.ts` (that gets the Schema Engine itself working, but the CLI's DMMF
// bootstrap for ANY command still needs the native query engine regardless).
//
// Consequences, both deliberate:
//   1. `npx tsc --noEmit`, `npx eslint .`, and `npx next build` will all fail on this
//      file today with "module '@prisma/client' has no exported member ..." — NOT
//      because the code below is wrong, but because the types it imports don't exist
//      on disk yet. This file is listed in `tsconfig.json`'s `exclude` array and in
//      `eslint.config.mjs`'s ignores for exactly this reason.
//   2. This is real, finished code — written exactly as it would be in a normal,
//      working Prisma project, against the actual field names/types/relations in
//      `prisma/schema.prisma`. It is NOT a stub. Once `prisma generate` has been run
//      somewhere with real network access (Vercel's build, or a developer's own
//      machine), this file typechecks and runs as-is — no further edits needed.
//   3. This file is NOT wired into `src/server/container.ts` yet. That composition-root
//      swap-over is intentionally deferred to whenever `prisma generate` can actually
//      run — see that file's own header comment.
// ============================================================================
//
// Mapping notes (see prisma/schema.prisma and src/modules/auth/types.ts for the
// authoritative shapes):
//
// - `AuthIdentity.ownerId` is a domain-type-only, DERIVED field (types.ts's own header
//   comment says so explicitly). The physical FK lives on `Owner.authIdentityId`, not
//   here — `prisma/schema.prisma`'s `AuthIdentity` model comment explains why (avoiding
//   two independently-nullable/unique columns drifting out of sync). Reads
//   (`findIdentityByEmail`/`findIdentityById`) resolve it via the `owner` back-relation
//   (`include: { owner: { select: { id: true } } }`), which is correct once an Owner row
//   has actually been linked.
//
// - `createIdentity`, however, is a special case worth flagging explicitly:
//   `CreateIdentityInput.ownerId` (repository.ts) is populated by `auth`'s service layer
//   (see `registerAccount` in service.ts) with the Owner id that a LATER, separate call
//   — `identityResolver.linkAccount` -> `customer.linkOwnerToAuthIdentity` — will use to
//   actually set `Owner.authIdentityId` on the database. At the instant `createIdentity`
//   itself runs, no Owner row points at the freshly-created AuthIdentity yet, so a
//   relation-based read here would (correctly, but unhelpfully) come back `null`. Rather
//   than return a technically-accurate-but-momentarily-stale `ownerId: null` that the
//   caller (`registerAccount`) would then hand back to its own caller as if the account
//   had no linked owner, this method returns the identity with `ownerId` taken directly
//   from `input.ownerId` — the value that will be true by the time the surrounding
//   `registerAccount` flow finishes (its very next step is the `linkAccount` call). This
//   mirrors how the in-memory Step 10 fake behaves (it stores exactly what it's given)
//   and keeps `registerAccount`'s returned `LoginResult.identity.ownerId` correct without
//   requiring `createIdentity` and `linkOwnerToAuthIdentity` to be merged into one
//   cross-module transaction (out of scope for this module's own repository).
//
// - `Session.id` IS the opaque session token (types.ts/schema.prisma both say so) — no
//   separate token column exists, so `findSessionByToken`/`deleteSession` key directly
//   off `Session.id`.
//
// - `deleteSession`/`deleteAllSessionsForIdentity` use `deleteMany` (not `delete`)
//   specifically so an already-gone/unknown token or identity is a silent no-op rather
//   than a thrown `P2025` — matching `AuthRepository.deleteSession`'s documented
//   "idempotent" contract.

import { PrismaClient, type AuthIdentity as PrismaAuthIdentity, type Session as PrismaSession } from "@prisma/client";
import type { CreateIdentityInput, CreateSessionInput, AuthRepository } from "../repository";
import type { AuthIdentity, AuthRole, Session } from "../types";

/** `AuthIdentity` row plus the one relation field this module ever needs from it. */
type AuthIdentityRowWithOwner = PrismaAuthIdentity & { owner: { id: string } | null };

function mapIdentity(row: AuthIdentityRowWithOwner): AuthIdentity {
  return {
    id: row.id,
    email: row.email,
    passwordHash: row.passwordHash,
    role: row.role as AuthRole,
    ownerId: row.owner?.id ?? null,
    createdAt: row.createdAt,
    verifiedAt: row.verifiedAt,
  };
}

function mapSession(row: PrismaSession): Session {
  return {
    id: row.id,
    authIdentityId: row.authIdentityId,
    role: row.role as AuthRole,
    createdAt: row.createdAt,
    expiresAt: row.expiresAt,
  };
}

export function createPrismaAuthRepository(prisma: PrismaClient): AuthRepository {
  return {
    async findIdentityByEmail(email: string): Promise<AuthIdentity | null> {
      const row = await prisma.authIdentity.findUnique({
        where: { email },
        include: { owner: { select: { id: true } } },
      });
      return row ? mapIdentity(row) : null;
    },

    async findIdentityById(id: string): Promise<AuthIdentity | null> {
      const row = await prisma.authIdentity.findUnique({
        where: { id },
        include: { owner: { select: { id: true } } },
      });
      return row ? mapIdentity(row) : null;
    },

    async createIdentity(input: CreateIdentityInput): Promise<AuthIdentity> {
      const row = await prisma.authIdentity.create({
        data: {
          email: input.email,
          passwordHash: input.passwordHash,
          role: input.role,
        },
      });
      // See the file header note above for why `ownerId` comes from `input`, not a
      // relation read, at this specific call site.
      return {
        id: row.id,
        email: row.email,
        passwordHash: row.passwordHash,
        role: row.role as AuthRole,
        ownerId: input.ownerId,
        createdAt: row.createdAt,
        verifiedAt: row.verifiedAt,
      };
    },

    async updatePasswordHash(identityId: string, passwordHash: string): Promise<void> {
      await prisma.authIdentity.update({
        where: { id: identityId },
        data: { passwordHash },
      });
    },

    async createSession(input: CreateSessionInput): Promise<Session> {
      const row = await prisma.session.create({
        data: {
          authIdentityId: input.authIdentityId,
          role: input.role,
        },
      });
      return mapSession(row);
    },

    async findSessionByToken(token: string): Promise<Session | null> {
      const row = await prisma.session.findUnique({ where: { id: token } });
      return row ? mapSession(row) : null;
    },

    async deleteSession(token: string): Promise<void> {
      // `deleteMany` (not `delete`) so an already-gone/unknown token is a silent no-op —
      // matches the interface's documented idempotency contract.
      await prisma.session.deleteMany({ where: { id: token } });
    },

    async deleteAllSessionsForIdentity(authIdentityId: string): Promise<void> {
      await prisma.session.deleteMany({ where: { authIdentityId } });
    },
  };
}
