-- ============================================================================
-- HAND-AUTHORED MIGRATION — read before trusting this file
-- ============================================================================
--
-- This migration.sql was NOT produced by `prisma migrate dev`. This container's
-- network policy blocks `binaries.prisma.sh` (the Prisma CLI's DMMF-computation
-- bootstrap unconditionally tries to download a native query-engine binary from
-- there, independent of the `engineType = "client"` / driver-adapters setup
-- already in `prisma/schema.prisma`'s generator block) — confirmed repeatedly
-- across every Prisma CLI subcommand (`generate`, `validate`, `format`,
-- `migrate dev`, `migrate diff`). See `aidlc-docs/audit.md`, the entry titled
-- "Investigation — Attempted to resolve the Prisma-binary network block before
-- Phase F", for the full investigation history.
--
-- Instead, this SQL was hand-translated from `prisma/schema.prisma`, field by
-- field and model by model, following Prisma's documented and observable
-- default naming/mapping conventions (verbatim model/field names as
-- table/column identifiers, `TIMESTAMP(3)` for `DateTime`, `TIME(3)`/`DATE` for
-- `@db.Time`/`@db.Date`, `<Table>_<field>_fkey` / `<Table>_<fields>_key` /
-- `<Table>_<field>_idx` constraint and index naming, CREATE TYPE ... CREATE
-- TABLE (inline PK only) ... CREATE INDEX ... ALTER TABLE ADD CONSTRAINT
-- FOREIGN KEY statement ordering, etc.) — the same structure Prisma's own
-- migration engine produces for a first migration.
--
-- VERIFICATION METHOD (this is the substitute for `prisma migrate dev`'s own
-- safety net, so it is named precisely rather than just asserted):
-- this exact file was executed, statement-by-statement, against a real,
-- live PostgreSQL server — not a mock, not a syntax linter — namely
-- `@electric-sql/pglite` (Postgres compiled to WASM, running fully offline,
-- no native binary download required). The verification script:
--   1. started a fresh PGlite instance and ran this entire file against it,
--      confirming every statement applies cleanly with zero errors;
--   2. queried `information_schema.tables`/`information_schema.columns`/
--      `pg_type` to confirm all 11 tables and all 6 enum types exist with the
--      expected columns and enum values;
--   3. positively exercised the single most important constraint in this
--      schema — `Appointment`'s `@@unique([groomerId, slotStart])`
--      (BR-AVAIL-5's DB-enforced slot-uniqueness guarantee) — by inserting two
--      appointments with the same (groomerId, slotStart) and confirming
--      Postgres itself rejects the second with a real unique-violation error.
-- Exact commands/output are recorded in this step's report, not repeated here.
--
-- RECOMMENDED FOLLOW-UP (do this before treating this file as final): once
-- `prisma generate`/`migrate dev` can reach the network (Vercel's build, or a
-- developer's own machine), run
--   npx prisma migrate diff --from-migrations prisma/migrations \
--     --to-schema-datamodel prisma/schema.prisma --script
-- from the repo root. An empty diff is the cheap, authoritative confirmation
-- that this hand-authored SQL matches what Prisma's own migration engine would
-- have generated, byte-for-byte in effect. Do not skip this once it's possible
-- to run — this file's correctness rests on careful translation + PGlite
-- execution, not on having actually been generated by Prisma's engine.
-- ============================================================================

-- CreateEnum
CREATE TYPE "AuthRole" AS ENUM ('customer', 'owner');

-- CreateEnum
CREATE TYPE "BookingActor" AS ENUM ('guest', 'account', 'owner');

-- CreateEnum
CREATE TYPE "PetSize" AS ENUM ('Small', 'Medium', 'Large', 'XL');

-- CreateEnum
CREATE TYPE "DayOfWeek" AS ENUM ('Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun');

-- CreateEnum
CREATE TYPE "AppointmentStatus" AS ENUM ('Booked', 'Completed', 'Cancelled', 'NoShow');

-- CreateEnum
CREATE TYPE "ReminderStatus" AS ENUM ('Pending', 'Sent', 'Cancelled');

-- CreateTable
CREATE TABLE "AuthIdentity" (
    "id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "passwordHash" TEXT NOT NULL,
    "role" "AuthRole" NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "verifiedAt" TIMESTAMP(3),

    CONSTRAINT "AuthIdentity_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Session" (
    "id" TEXT NOT NULL,
    "authIdentityId" TEXT NOT NULL,
    "role" "AuthRole" NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expiresAt" TIMESTAMP(3),

    CONSTRAINT "Session_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Owner" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "phone" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "address" TEXT,
    "notes" TEXT,
    "authIdentityId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Owner_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Pet" (
    "id" TEXT NOT NULL,
    "ownerId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "breed" TEXT NOT NULL,
    "size" "PetSize" NOT NULL,
    "age" INTEGER,
    "temperamentNotes" TEXT,
    "allergyMedicalNotes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Pet_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Groomer" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Groomer_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Service" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "price" DECIMAL(10,2) NOT NULL,
    "durationMinutes" INTEGER NOT NULL,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Service_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "WorkingHoursRule" (
    "id" TEXT NOT NULL,
    "dayOfWeek" "DayOfWeek" NOT NULL,
    "isOpen" BOOLEAN NOT NULL,
    "openTime" TIME(3),
    "closeTime" TIME(3),

    CONSTRAINT "WorkingHoursRule_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TimeOff" (
    "id" TEXT NOT NULL,
    "startDate" DATE NOT NULL,
    "endDate" DATE NOT NULL,
    "reason" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TimeOff_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Appointment" (
    "id" TEXT NOT NULL,
    "bookingReference" TEXT NOT NULL,
    "ownerId" TEXT NOT NULL,
    "groomerId" TEXT NOT NULL,
    "slotStart" TIMESTAMP(3) NOT NULL,
    "slotEnd" TIMESTAMP(3) NOT NULL,
    "status" "AppointmentStatus" NOT NULL DEFAULT 'Booked',
    "createdBy" "BookingActor" NOT NULL,
    "isOverride" BOOLEAN NOT NULL DEFAULT false,
    "hasConflict" BOOLEAN NOT NULL DEFAULT false,
    "flaggedForReview" BOOLEAN NOT NULL DEFAULT false,
    "notificationFailed" BOOLEAN NOT NULL DEFAULT false,
    "visitNotes" TEXT,
    "cancelledAt" TIMESTAMP(3),
    "cancelledBy" "BookingActor",
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Appointment_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AppointmentLineItem" (
    "id" TEXT NOT NULL,
    "appointmentId" TEXT NOT NULL,
    "petId" TEXT NOT NULL,
    "serviceId" TEXT NOT NULL,
    "priceSnapshot" DECIMAL(10,2) NOT NULL,
    "durationSnapshotMinutes" INTEGER NOT NULL,

    CONSTRAINT "AppointmentLineItem_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ScheduledReminder" (
    "id" TEXT NOT NULL,
    "appointmentId" TEXT NOT NULL,
    "sendAt" TIMESTAMP(3),
    "status" "ReminderStatus" NOT NULL DEFAULT 'Pending',

    CONSTRAINT "ScheduledReminder_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "AuthIdentity_email_key" ON "AuthIdentity"("email");

-- CreateIndex
CREATE INDEX "Session_authIdentityId_idx" ON "Session"("authIdentityId");

-- CreateIndex
CREATE UNIQUE INDEX "Owner_authIdentityId_key" ON "Owner"("authIdentityId");

-- CreateIndex
CREATE INDEX "Pet_ownerId_idx" ON "Pet"("ownerId");

-- CreateIndex
CREATE UNIQUE INDEX "WorkingHoursRule_dayOfWeek_key" ON "WorkingHoursRule"("dayOfWeek");

-- CreateIndex
CREATE UNIQUE INDEX "Appointment_bookingReference_key" ON "Appointment"("bookingReference");

-- CreateIndex
CREATE INDEX "Appointment_slotStart_idx" ON "Appointment"("slotStart");

-- CreateIndex
CREATE INDEX "Appointment_ownerId_idx" ON "Appointment"("ownerId");

-- CreateIndex
CREATE UNIQUE INDEX "Appointment_groomerId_slotStart_key" ON "Appointment"("groomerId", "slotStart");

-- CreateIndex
CREATE INDEX "AppointmentLineItem_appointmentId_idx" ON "AppointmentLineItem"("appointmentId");

-- CreateIndex
CREATE INDEX "ScheduledReminder_appointmentId_idx" ON "ScheduledReminder"("appointmentId");

-- CreateIndex
CREATE INDEX "ScheduledReminder_status_sendAt_idx" ON "ScheduledReminder"("status", "sendAt");

-- AddForeignKey
ALTER TABLE "Session" ADD CONSTRAINT "Session_authIdentityId_fkey" FOREIGN KEY ("authIdentityId") REFERENCES "AuthIdentity"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Owner" ADD CONSTRAINT "Owner_authIdentityId_fkey" FOREIGN KEY ("authIdentityId") REFERENCES "AuthIdentity"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Pet" ADD CONSTRAINT "Pet_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "Owner"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Appointment" ADD CONSTRAINT "Appointment_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "Owner"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Appointment" ADD CONSTRAINT "Appointment_groomerId_fkey" FOREIGN KEY ("groomerId") REFERENCES "Groomer"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AppointmentLineItem" ADD CONSTRAINT "AppointmentLineItem_appointmentId_fkey" FOREIGN KEY ("appointmentId") REFERENCES "Appointment"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AppointmentLineItem" ADD CONSTRAINT "AppointmentLineItem_petId_fkey" FOREIGN KEY ("petId") REFERENCES "Pet"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AppointmentLineItem" ADD CONSTRAINT "AppointmentLineItem_serviceId_fkey" FOREIGN KEY ("serviceId") REFERENCES "Service"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ScheduledReminder" ADD CONSTRAINT "ScheduledReminder_appointmentId_fkey" FOREIGN KEY ("appointmentId") REFERENCES "Appointment"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
