// Prisma-backed implementation of `BookingRepository` (src/modules/booking/repository.ts).
//
// ============================================================================
// READ THIS BEFORE TOUCHING THIS FILE
// ============================================================================
// This file imports `@prisma/client`, whose TypeScript types are GENERATED by
// `npx prisma generate` from `prisma/schema.prisma`. That command cannot succeed in
// this dev container: `prisma generate`'s internal DMMF-computation step needs the
// native query-engine binary from `binaries.prisma.sh`, which this container's network
// policy blocks — confirmed even with the JS/WASM schema-engine mode already configured
// in `prisma.config.ts` (that gets the Schema Engine itself working, but the CLI's DMMF
// bootstrap for ANY command still needs the native query engine regardless).
//
// Consequences, both deliberate:
//   1. `npx tsc --noEmit`, `npx eslint .`, and `npx next build` will all fail on this
//      file today with "module '@prisma/client' has no exported member ..." — NOT
//      because the code below is wrong, but because the types it imports don't exist
//      on disk yet. This file is listed in `tsconfig.json`'s `exclude` array and in
//      `eslint.config.mjs`'s ignores for exactly this reason.
//   2. This is real, finished code — written exactly as it would be in a normal,
//      working Prisma project, against the actual field names/types/relations in
//      `prisma/schema.prisma`. It is NOT a stub. Once `prisma generate` has been run
//      somewhere with real network access (Vercel's build, or a developer's own
//      machine), this file typechecks and runs as-is — no further edits needed.
//   3. This file is NOT wired into `src/server/container.ts` yet. That composition-root
//      swap-over is intentionally deferred to whenever `prisma generate` can actually
//      run — see that file's own header comment.
// ============================================================================
//
// ============================================================================
// ARCHITECTURAL NOTE — this is where BR-AVAIL-5's real atomicity guarantee lives
// ============================================================================
// `src/modules/availability/prisma/repository.ts`'s own file-level architectural note
// (read that first) explains why the literal NFR Design pattern from
// `nfr-design-patterns.md` ("Slot-claim concurrency": attempt the `Appointment` insert
// directly inside a transaction; catch a constraint violation; translate it to "slot no
// longer available") cannot be implemented in `availability`'s `claimSlot`/
// `forceClaimSlot` — there is no `SlotClaim` table, and `ClaimSlotInput` carries none of
// the fields (`ownerId`, `bookingReference`, `createdBy`, line items, ...) needed to
// insert a real `Appointment` row. `availability`'s methods there are a best-effort,
// late re-check only.
//
// THE REAL GUARANTEE LIVES HERE, in `createAppointment` below — the one place in the
// whole system where a complete, insertable `Appointment` row actually exists at the
// moment of the DB call:
//
//   - `createAppointment` attempts `tx.appointment.create(...)` directly inside a
//     `prisma.$transaction`, alongside the `AppointmentLineItem` inserts (see the
//     price/duration snapshot note below) — no `SELECT ... FOR UPDATE`, no
//     application-level mutex, per nfr-design-patterns.md's explicit instruction.
//   - `Appointment`'s `@@unique([groomerId, slotStart])` constraint (schema.prisma) is
//     the actual, database-enforced, race-proof guarantee: if two concurrent callers
//     both pass availability's best-effort pre-check for the exact same
//     `(groomerId, slotStart)`, only one of the two competing `INSERT`s can win —
//     Postgres itself serializes that, not application code.
//   - The loser's insert fails with a `PrismaClientKnownRequestError` whose
//     `code === "P2002"`. This file catches exactly that, inspects `err.meta?.target`
//     to confirm the violated constraint is the `(groomerId, slotStart)` one (as opposed
//     to `Appointment.bookingReference`'s own, unrelated unique constraint — see below),
//     and re-throws it as `SlotNotAvailableError` (./errors) — the exact error class
//     `booking/service.ts` already both expects and handles: `createBooking`'s and
//     `rescheduleBooking`'s only `try/catch` around the booking-vs-availability boundary
//     today wraps `availability.claimSlot`, catching `AvailabilitySlotNotAvailableError`
//     and re-throwing this module's OWN `SlotNotAvailableError` (booking/errors.ts) — so
//     throwing that identical class here means it propagates out of
//     `persistAppointment`/`createBooking` uncaught (that function's own `catch` only
//     matches `BookingReferenceCollisionError`, see below) and reaches the same caller-
//     visible error type either way. No change to service.ts was necessary or made —
//     this repository method's contract (repository.ts's own doc comment on
//     `createAppointment`, which already names `BookingReferenceCollisionError`
//     explicitly) is satisfied by adding this second, equally real translated error.
//   - `Appointment.bookingReference` carries its OWN, unrelated `@unique` constraint
//     (BR-BOOK-8). A P2002 on THAT constraint is translated to
//     `BookingReferenceCollisionError` instead — the error `persistAppointment`
//     (service.ts) already explicitly catches and retries with a freshly generated
//     reference. `translateCreateAppointmentError` below distinguishes the two
//     constraints by inspecting which column(s) `err.meta.target` names.
//
// This does not change anything about `availability`'s own file, which is correct as
// written and already documents this same architectural split from its side. Per that
// file's note, Step 18's concurrent-request integration test needs to drive concurrent
// callers all the way through `createBooking`/this method to actually exercise the
// guarantee — `availability.claimSlot` alone cannot prove it.
// ============================================================================
//
// Other mapping notes:
// - Price/duration snapshot (BR-CAT-4, booking-domain-entities.md, this module's own
//   repository.ts doc comment on `createAppointment`): `CreateAppointmentInput.lineItems`
//   arrives with `priceSnapshot`/`durationSnapshotMinutes` already computed by
//   service.ts's `resolveLineItems` (read from the live `Service` row at the moment of
//   booking, per catalog's `getService`). This method's only job is to PERSIST that
//   already-computed snapshot — each `AppointmentLineItem` row is inserted with those
//   exact values, inside the SAME `prisma.$transaction` as the `Appointment` row itself,
//   so a reader can never observe an `Appointment` with an incomplete or missing set of
//   line items (all-or-nothing).
// - `Groomer` is `customer`'s exported type (types.ts imports it directly, matching
//   repository.ts's own import) — `findDefaultGroomer` maps a raw `Groomer` Prisma row
//   onto it the same simple 1:1 way `customer/prisma/repository.ts` does for the rows it
//   owns; no enum-casing needed (`Groomer` has none).
// - `Appointment.status`/`createdBy`/`cancelledBy` are Prisma enums (`AppointmentStatus`,
//   `BookingActor`) whose members are string-identical to this module's own domain unions
//   in types.ts — assigned with a type-level cast, the same pattern `auth`'s
//   `AuthIdentity.role` and `customer`'s `Pet.size` already use.
// - `AppointmentLineItem.priceSnapshot` is `Decimal @db.Decimal(10, 2)` — converted with
//   `Number(...)` at the read boundary, the same pattern as `catalog`'s `Service.price`.
// - `updateStatus`/`updateSlot`/`updateVisitNotes` all pass their input fields straight
//   through to Prisma's `update` `data` — `UpdateStatusInput.cancelledAt`/`cancelledBy`
//   are optional (`undefined` = leave untouched, explicit `null` = clear), matching
//   Prisma's own `update` semantics exactly, the same pattern already established by
//   `customer/prisma/repository.ts`'s `updateOwner`/`updatePet`.
// - `listByDateRange`/`countAppointmentsInRange`-style range filters throughout this
//   codebase are half-open `[start, end)` (see reporting's `DateRange` doc comment,
//   which states this explicitly, and `tests/fakes/booking.fake.ts`'s own
//   `listByDateRange` fake implementation, which filters `>= start && < end`) — this
//   method matches that: `slotStart: { gte: range.start, lt: range.end }`.
// - `listByOwner`/`listByDateRange` order by `slotStart` (ascending for a date-range
//   listing — SO-1's admin calendar naturally wants chronological order; descending for
//   "my bookings" — RC-3's most-relevant-first expectation) since neither the fake nor
//   any interface doc comment pins down an order; a judgment call, flagged here rather
//   than silently made.

import {
  Prisma,
  PrismaClient,
  type Appointment as PrismaAppointment,
  type AppointmentLineItem as PrismaAppointmentLineItem,
  type Groomer as PrismaGroomer,
} from "@prisma/client";
import type { Groomer } from "@/modules/customer";
import { BookingReferenceCollisionError, SlotNotAvailableError } from "../errors";
import type { BookingRepository, CreateAppointmentInput, UpdateStatusInput } from "../repository";
import type { AppointmentLineItem, AppointmentStatus, AppointmentWithLineItems, BookingActor, DateRange } from "../types";

function mapGroomer(row: PrismaGroomer): Groomer {
  return {
    id: row.id,
    name: row.name,
    active: row.active,
    createdAt: row.createdAt,
  };
}

function mapLineItem(row: PrismaAppointmentLineItem): AppointmentLineItem {
  return {
    id: row.id,
    appointmentId: row.appointmentId,
    petId: row.petId,
    serviceId: row.serviceId,
    priceSnapshot: Number(row.priceSnapshot),
    durationSnapshotMinutes: row.durationSnapshotMinutes,
  };
}

type AppointmentRowWithLineItems = PrismaAppointment & { lineItems: PrismaAppointmentLineItem[] };

function mapAppointment(row: AppointmentRowWithLineItems): AppointmentWithLineItems {
  return {
    id: row.id,
    bookingReference: row.bookingReference,
    ownerId: row.ownerId,
    groomerId: row.groomerId,
    slotStart: row.slotStart,
    slotEnd: row.slotEnd,
    status: row.status as AppointmentStatus,
    createdBy: row.createdBy as BookingActor,
    isOverride: row.isOverride,
    hasConflict: row.hasConflict,
    flaggedForReview: row.flaggedForReview,
    notificationFailed: row.notificationFailed,
    visitNotes: row.visitNotes,
    cancelledAt: row.cancelledAt,
    cancelledBy: row.cancelledBy as BookingActor | null,
    createdAt: row.createdAt,
    lineItems: row.lineItems.map(mapLineItem),
  };
}

/**
 * Translates a `P2002` unique-constraint violation from `createAppointment`'s insert
 * into the specific domain error the violated constraint actually means — see the
 * file-level architectural note above. Anything else (a different Prisma error code, or
 * a non-Prisma error) passes through unchanged.
 *
 * `err.meta.target` for a Postgres unique-constraint violation is, depending on Prisma's
 * engine/introspection path, either an array of the violated columns' field names (e.g.
 * `["groomerId", "slotStart"]`) or the raw constraint name as a single string (e.g.
 * `"Appointment_groomerId_slotStart_key"`). Normalizing to a lowercase array and checking
 * for substring membership handles both forms without needing to know which one a given
 * Prisma/Postgres version actually returns.
 */
function translateCreateAppointmentError(err: unknown): unknown {
  if (!(err instanceof Prisma.PrismaClientKnownRequestError) || err.code !== "P2002") {
    return err;
  }

  const rawTarget = err.meta?.target;
  const targetParts = (Array.isArray(rawTarget) ? rawTarget : typeof rawTarget === "string" ? [rawTarget] : []).map((part) =>
    String(part).toLowerCase(),
  );
  const namesConstraint = (...columns: string[]) => columns.every((col) => targetParts.some((part) => part.includes(col)));

  if (namesConstraint("groomerid", "slotstart")) {
    // The `@@unique([groomerId, slotStart])` constraint — BR-AVAIL-5's real, DB-enforced
    // atomicity guarantee. Someone else's insert won the race for this exact slot.
    return new SlotNotAvailableError();
  }
  if (namesConstraint("bookingreference")) {
    // `Appointment.bookingReference`'s own unique constraint (BR-BOOK-8) — an unrelated
    // collision on the random reference suffix. `persistAppointment` (service.ts)
    // already catches exactly this class and retries with a fresh reference.
    return new BookingReferenceCollisionError();
  }
  return err;
}

export function createPrismaBookingRepository(prisma: PrismaClient): BookingRepository {
  return {
    async findDefaultGroomer(): Promise<Groomer | null> {
      // v1 has exactly one (active) Groomer (FR-2) — same resolution pattern
      // `availability/prisma/repository.ts`'s `resolveActiveGroomerId` uses.
      const row = await prisma.groomer.findFirst({
        where: { active: true },
        orderBy: { createdAt: "asc" },
      });
      return row ? mapGroomer(row) : null;
    },

    async createAppointment(input: CreateAppointmentInput): Promise<AppointmentWithLineItems> {
      try {
        const { appointment, lineItems } = await prisma.$transaction(async (tx) => {
          // The insert-and-catch-P2002 attempt itself — see the file-level
          // architectural note above for why this exact call, not `availability`'s
          // `claimSlot`, is where BR-AVAIL-5's real guarantee lives.
          const appointment = await tx.appointment.create({
            data: {
              id: input.id,
              bookingReference: input.bookingReference,
              ownerId: input.ownerId,
              groomerId: input.groomerId,
              slotStart: input.slotStart,
              slotEnd: input.slotEnd,
              status: input.status,
              createdBy: input.createdBy,
              isOverride: input.isOverride,
              hasConflict: input.hasConflict,
              visitNotes: input.visitNotes,
            },
          });

          // Price/duration snapshot write (BR-CAT-4) — persisted atomically with the
          // Appointment row above, inside the same transaction, so the two can never
          // observably diverge (an Appointment with zero/partial line items).
          const lineItems = await Promise.all(
            input.lineItems.map((lineItem) =>
              tx.appointmentLineItem.create({
                data: {
                  appointmentId: appointment.id,
                  petId: lineItem.petId,
                  serviceId: lineItem.serviceId,
                  priceSnapshot: lineItem.priceSnapshot,
                  durationSnapshotMinutes: lineItem.durationSnapshotMinutes,
                },
              }),
            ),
          );

          return { appointment, lineItems };
        });

        return mapAppointment({ ...appointment, lineItems });
      } catch (err) {
        throw translateCreateAppointmentError(err);
      }
    },

    async findAppointmentById(appointmentId: string): Promise<AppointmentWithLineItems | null> {
      const row = await prisma.appointment.findUnique({
        where: { id: appointmentId },
        include: { lineItems: true },
      });
      return row ? mapAppointment(row) : null;
    },

    async findAppointmentByReference(bookingReference: string): Promise<AppointmentWithLineItems | null> {
      const row = await prisma.appointment.findUnique({
        where: { bookingReference },
        include: { lineItems: true },
      });
      return row ? mapAppointment(row) : null;
    },

    async updateStatus(appointmentId: string, fields: UpdateStatusInput): Promise<AppointmentWithLineItems> {
      const row = await prisma.appointment.update({
        where: { id: appointmentId },
        // `undefined` fields are left untouched by Prisma's `update` — matches
        // `UpdateStatusInput`'s optional-vs-nullable contract directly (see e.g.
        // `markNoShow`'s call, which supplies only `status`).
        data: {
          status: fields.status,
          cancelledAt: fields.cancelledAt,
          cancelledBy: fields.cancelledBy,
        },
        include: { lineItems: true },
      });
      return mapAppointment(row);
    },

    async updateSlot(appointmentId: string, fields: { slotStart: Date; slotEnd: Date }): Promise<AppointmentWithLineItems> {
      const row = await prisma.appointment.update({
        where: { id: appointmentId },
        data: { slotStart: fields.slotStart, slotEnd: fields.slotEnd },
        include: { lineItems: true },
      });
      return mapAppointment(row);
    },

    async updateVisitNotes(appointmentId: string, visitNotes: string | null): Promise<AppointmentWithLineItems> {
      const row = await prisma.appointment.update({
        where: { id: appointmentId },
        data: { visitNotes },
        include: { lineItems: true },
      });
      return mapAppointment(row);
    },

    async listByOwner(ownerId: string): Promise<AppointmentWithLineItems[]> {
      const rows = await prisma.appointment.findMany({
        where: { ownerId },
        include: { lineItems: true },
        orderBy: { slotStart: "desc" },
      });
      return rows.map(mapAppointment);
    },

    async listByDateRange(range: DateRange): Promise<AppointmentWithLineItems[]> {
      const rows = await prisma.appointment.findMany({
        where: { slotStart: { gte: range.start, lt: range.end } },
        include: { lineItems: true },
        orderBy: { slotStart: "asc" },
      });
      return rows.map(mapAppointment);
    },

    async setFlaggedForReview(appointmentIds: string[], flagged: boolean): Promise<void> {
      if (appointmentIds.length === 0) return; // documented no-op (repository.ts)
      await prisma.appointment.updateMany({
        where: { id: { in: appointmentIds } },
        data: { flaggedForReview: flagged },
      });
    },
  };
}
