// Prisma-backed implementation of `CustomerRepository` (src/modules/customer/repository.ts).
//
// ============================================================================
// READ THIS BEFORE TOUCHING THIS FILE
// ============================================================================
// This file imports `@prisma/client`, whose TypeScript types are GENERATED by
// `npx prisma generate` from `prisma/schema.prisma`. That command cannot succeed in
// this dev container: `prisma generate`'s internal DMMF-computation step needs the
// native query-engine binary from `binaries.prisma.sh`, which this container's network
// policy blocks — confirmed even with the JS/WASM schema-engine mode already configured
// in `prisma.config.ts` (that gets the Schema Engine itself working, but the CLI's DMMF
// bootstrap for ANY command still needs the native query engine regardless).
//
// Consequences, both deliberate:
//   1. `npx tsc --noEmit`, `npx eslint .`, and `npx next build` will all fail on this
//      file today with "module '@prisma/client' has no exported member ..." — NOT
//      because the code below is wrong, but because the types it imports don't exist
//      on disk yet. This file is listed in `tsconfig.json`'s `exclude` array and in
//      `eslint.config.mjs`'s ignores for exactly this reason.
//   2. This is real, finished code — written exactly as it would be in a normal,
//      working Prisma project, against the actual field names/types/relations in
//      `prisma/schema.prisma`. It is NOT a stub. Once `prisma generate` has been run
//      somewhere with real network access (Vercel's build, or a developer's own
//      machine), this file typechecks and runs as-is — no further edits needed.
//   3. This file is NOT wired into `src/server/container.ts` yet. That composition-root
//      swap-over is intentionally deferred to whenever `prisma generate` can actually
//      run — see that file's own header comment.
// ============================================================================
//
// Mapping notes:
// - `Owner` and `Pet` rows map 1:1 onto `customer`'s own `Owner`/`Pet` domain types
//   (same field names, same nullability) — no enum-casing or renaming needed, unlike
//   `catalog`'s `Service.price` (Decimal -> number). `Pet.size` is a Prisma enum
//   (`PetSize`) whose members (`Small`/`Medium`/`Large`/`XL`) are string-identical to the
//   domain `PetSize` union in types.ts, so it's assigned directly with a type-level cast,
//   not a value-level mapping table.
// - `Owner.email`/`Owner.phone` are plain (non-unique) columns in the schema — BR-CUST-1's
//   "exact match" lookups (`findOwnerByEmail`/`findOwnerByPhone`) use `findFirst`, not
//   `findUnique`, and order by `createdAt asc` for a deterministic pick in the (expected
//   to be rare) case more than one Owner row shares an email/phone.

import { PrismaClient, type Owner as PrismaOwner, type Pet as PrismaPet } from "@prisma/client";
import type { CustomerRepository } from "../repository";
import type {
  ContactInfo,
  Owner,
  OwnerUpdateInput,
  Pet,
  PetCreateInput,
  PetSize,
  PetUpdateInput,
} from "../types";

function mapOwner(row: PrismaOwner): Owner {
  return {
    id: row.id,
    name: row.name,
    phone: row.phone,
    email: row.email,
    address: row.address,
    notes: row.notes,
    authIdentityId: row.authIdentityId,
    createdAt: row.createdAt,
  };
}

function mapPet(row: PrismaPet): Pet {
  return {
    id: row.id,
    ownerId: row.ownerId,
    name: row.name,
    breed: row.breed,
    size: row.size as PetSize,
    age: row.age,
    temperamentNotes: row.temperamentNotes,
    allergyMedicalNotes: row.allergyMedicalNotes,
    createdAt: row.createdAt,
  };
}

export function createPrismaCustomerRepository(prisma: PrismaClient): CustomerRepository {
  return {
    async findOwnerById(ownerId: string): Promise<Owner | null> {
      const row = await prisma.owner.findUnique({ where: { id: ownerId } });
      return row ? mapOwner(row) : null;
    },

    async findOwnerByEmail(email: string): Promise<Owner | null> {
      const row = await prisma.owner.findFirst({
        where: { email },
        orderBy: { createdAt: "asc" },
      });
      return row ? mapOwner(row) : null;
    },

    async findOwnerByPhone(phone: string): Promise<Owner | null> {
      const row = await prisma.owner.findFirst({
        where: { phone },
        orderBy: { createdAt: "asc" },
      });
      return row ? mapOwner(row) : null;
    },

    async createOwner(input: ContactInfo): Promise<Owner> {
      const row = await prisma.owner.create({
        data: {
          name: input.name,
          phone: input.phone,
          email: input.email,
        },
      });
      return mapOwner(row);
    },

    async updateOwner(ownerId: string, fields: OwnerUpdateInput): Promise<Owner> {
      const row = await prisma.owner.update({
        where: { id: ownerId },
        // Prisma's `update` treats an `undefined` field as "leave untouched" and an
        // explicit `null` as "set to null" — exactly matching `OwnerUpdateInput`'s own
        // optional-vs-nullable contract, so the input can be passed straight through.
        data: {
          name: fields.name,
          phone: fields.phone,
          email: fields.email,
          address: fields.address,
          notes: fields.notes,
        },
      });
      return mapOwner(row);
    },

    async linkOwnerToAuthIdentity(ownerId: string, authIdentityId: string): Promise<Owner> {
      const row = await prisma.owner.update({
        where: { id: ownerId },
        data: { authIdentityId },
      });
      return mapOwner(row);
    },

    async listPetsByOwner(ownerId: string): Promise<Pet[]> {
      const rows = await prisma.pet.findMany({
        where: { ownerId },
        orderBy: { createdAt: "asc" },
      });
      return rows.map(mapPet);
    },

    async findPetById(petId: string): Promise<Pet | null> {
      const row = await prisma.pet.findUnique({ where: { id: petId } });
      return row ? mapPet(row) : null;
    },

    async createPet(input: PetCreateInput): Promise<Pet> {
      const row = await prisma.pet.create({
        data: {
          ownerId: input.ownerId,
          name: input.name,
          breed: input.breed,
          size: input.size,
          age: input.age ?? null,
          temperamentNotes: input.temperamentNotes ?? null,
          allergyMedicalNotes: input.allergyMedicalNotes ?? null,
        },
      });
      return mapPet(row);
    },

    async updatePet(petId: string, fields: PetUpdateInput): Promise<Pet> {
      const row = await prisma.pet.update({
        where: { id: petId },
        data: {
          name: fields.name,
          breed: fields.breed,
          size: fields.size,
          age: fields.age,
          temperamentNotes: fields.temperamentNotes,
          allergyMedicalNotes: fields.allergyMedicalNotes,
        },
      });
      return mapPet(row);
    },
  };
}
