// Prisma-backed implementation of `AvailabilityRepository`
// (src/modules/availability/repository.ts).
//
// ============================================================================
// READ THIS BEFORE TOUCHING THIS FILE
// ============================================================================
// This file imports `@prisma/client`, whose TypeScript types are GENERATED by
// `npx prisma generate` from `prisma/schema.prisma`. That command cannot succeed in
// this dev container: `prisma generate`'s internal DMMF-computation step needs the
// native query-engine binary from `binaries.prisma.sh`, which this container's network
// policy blocks — confirmed even with the JS/WASM schema-engine mode already configured
// in `prisma.config.ts` (that gets the Schema Engine itself working, but the CLI's DMMF
// bootstrap for ANY command still needs the native query engine regardless).
//
// Consequences, both deliberate:
//   1. `npx tsc --noEmit`, `npx eslint .`, and `npx next build` will all fail on this
//      file today with "module '@prisma/client' has no exported member ..." — NOT
//      because the code below is wrong, but because the types it imports don't exist
//      on disk yet. This file is listed in `tsconfig.json`'s `exclude` array and in
//      `eslint.config.mjs`'s ignores for exactly this reason.
//   2. This is real, finished code — written exactly as it would be in a normal,
//      working Prisma project, against the actual field names/types/relations in
//      `prisma/schema.prisma`. It is NOT a stub. Once `prisma generate` has been run
//      somewhere with real network access (Vercel's build, or a developer's own
//      machine), this file typechecks and runs as-is — no further edits needed.
//   3. This file is NOT wired into `src/server/container.ts` yet. That composition-root
//      swap-over is intentionally deferred to whenever `prisma generate` can actually
//      run — see that file's own header comment.
// ============================================================================
//
// ============================================================================
// ARCHITECTURAL NOTE — `claimSlot`/`forceClaimSlot` and BR-AVAIL-5's atomicity
// guarantee (READ THIS BEFORE CHANGING `booking`'s repository either — this affects it)
// ============================================================================
// `nfr-design-patterns.md`'s "Slot-claim concurrency" pattern and this module's own
// `errors.ts` header comment on `SlotConstraintViolationError` both describe the
// Prisma-backed `claimSlot` as directly attempting the `Appointment` insert inside a
// transaction and catching a real Postgres unique-constraint violation on
// `(groomerId, slotStart)`. Having now read `prisma/schema.prisma`,
// `src/modules/availability/repository.ts`'s `ClaimSlotInput` shape, and
// `src/modules/booking/service.ts`'s actual call site, that literal design is NOT
// achievable as written, for a concrete, structural reason — documented here in full
// because it changes what `booking`'s own Step 17 repository work needs to do:
//
//   - There is no `SlotClaim` table. `prisma/schema.prisma`'s header comment confirms
//     this is intentional: `Slot` and `SlotClaim` are computed/conceptual, never stored
//     rows. The ONLY table carrying the `(groomerId, slotStart)` DB uniqueness
//     constraint is `Appointment` itself (`@@unique([groomerId, slotStart])`).
//
//   - `ClaimSlotInput` (repository.ts) is exactly `{ appointmentId, start, end }`. It
//     carries no `ownerId`, `bookingReference`, or `createdBy` — all three are required
//     (`NOT NULL`), foreign-key- or uniqueness-constrained columns on `Appointment`
//     that `availability` simply has no way to supply.
//
//   - `booking/service.ts`'s `createBooking`/`createOverrideBooking` confirm why: they
//     generate `appointmentId` client-side and call `availability.claimSlot`/
//     `forceClaimSlot` FIRST — before `persistAppointment` -> `repository.createAppointment`
//     assembles and inserts the full `Appointment` row (with the SAME id). By the time
//     `claimSlot` runs, no valid, insertable `Appointment` row exists yet for
//     `availability` to attempt inserting on `booking`'s behalf.
//
// Given `ClaimSlotInput`'s shape and `booking/service.ts`'s call order are both already
// approved, out-of-scope work for this pass (repository.ts is Step 6, service.ts is
// Step 7 — this pass is Step 17, repository *implementations* against the interfaces as
// given), the sensible resolution — and the one actually implemented below — is:
//
//   RESOLUTION: The real, DB-enforced insert-and-catch-`P2002` guarantee for BR-AVAIL-5
//   can only be realized where a full, insertable `Appointment` row actually exists:
//   `booking`'s `createAppointment` repository method. THAT insert — not this file's
//   `claimSlot` — is where the literal NFR Design pattern (attempt the `Appointment`
//   insert, catch `PrismaClientKnownRequestError` with `code === "P2002"` targeting
//   `Appointment_groomerId_slotStart_key`, translate to a "slot taken" error) must live.
//   This is the single most important thing for whoever implements `booking`'s Step 17
//   half to know — it is flagged prominently in this Code Generation pass's report.
//
//   Given that, `claimSlot`/`forceClaimSlot` here are implemented as faithfully to their
//   OWN documented contract (repository.ts, errors.ts) as this schema allows:
//     - `claimSlot` resolves the (single, v1) active groomer and performs a real,
//       current-as-of-this-query read against the live `Appointment` table for any
//       existing row — ANY status, matching the real DB unique index's own scope, which
//       (per schema.prisma's own note) does not exempt Cancelled/NoShow rows — at this
//       exact `(groomerId, slotStart)`. A hit throws `SlotConstraintViolationError`,
//       exactly as the interface requires. This closes the race window further than the
//       service layer's own buffered/windowed pre-check (`evaluateNormalAvailability`,
//       which already ran before this method is called) by re-checking the literal DB
//       constraint's exact scope at a later instant — but it is honestly NOT the final,
//       airtight atomicity guarantee, since there is still a gap between this read and
//       `booking`'s later insert. The insert-and-catch on `booking`'s side (see above)
//       is what actually closes that gap for real, concurrent, simultaneous callers.
//     - `forceClaimSlot` has nothing to persist here either (same reasoning), and is
//       implemented as an intentional no-op, exactly mirroring this same module's own
//       already-established `releaseSlot()` precedent (service.ts: "no separate release
//       action needed on availability's side ... since availability computes live from
//       Appointment data rather than a stored reservation"). `forceClaimSlot`'s
//       documented contract already says it carries no atomicity guarantee at all, so a
//       no-op here changes nothing about its observable behavior — the resulting
//       Appointment row (with `isOverride`/`hasConflict` already computed by
//       `AvailabilityService.forceClaimSlot` before this call) is what `booking` persists.
//
// This does NOT weaken BR-AVAIL-5 in the finished system — it relocates where the DB
// constraint is actually caught to the one place a valid row exists to trigger it. It
// DOES mean Step 18's concurrent-request integration test (proving BR-AVAIL-5's
// atomicity against a real Postgres instance) needs to drive concurrent callers all the
// way through `booking.createBooking`/`repository.createAppointment`, not stop at
// `availability.claimSlot` alone — `availability`'s own `claimSlot` cannot, by itself,
// prove the guarantee this schema's constraint actually provides.
// ============================================================================
//
// Other mapping notes:
// - `WorkingHoursRule.openTime`/`closeTime` are `DateTime? @db.Time` columns — Postgres
//   `TIME` has no calendar date, and Prisma represents it as a JS `Date` anchored to the
//   Unix epoch date (1970-01-01) carrying only the time-of-day in UTC. The domain type
//   (types.ts) represents the same value as a plain `"HH:mm"` string (its own header
//   comment calls this conversion out as this file's job, the same pattern as
//   `catalog`'s `Service.price` Decimal->number conversion). `hhmmToTimeColumn`/
//   `timeColumnToHhmm` below do that conversion at the boundary.
// - `TimeOff.startDate`/`endDate` are `DateTime @db.Date` — date-only, no time-of-day
//   conversion needed; they pass through as `Date` objects unchanged, same as the
//   domain type.
// - `listWorkingHours` sorts by the natural Mon..Sun week order (not `dayOfWeek`'s
//   alphabetical enum ordering, which Postgres/Prisma would otherwise apply) — a
//   presentation nicety `WorkingHoursRule[]`'s consumers reasonably expect and that
//   `replaceWorkingHours`'s own input (`everydayOpenSchedule` et al.) is always
//   constructed in.

import { PrismaClient, type DayOfWeek, type TimeOff as PrismaTimeOff, type WorkingHoursRule as PrismaWorkingHoursRule } from "@prisma/client";
import { SlotConstraintViolationError } from "../errors";
import type { AvailabilityRepository, ClaimSlotInput, OccupiedRange } from "../repository";
import type { DayOfWeek as DomainDayOfWeek, TimeOff, TimeOffCreateInput, WorkingHoursRule, WorkingHoursRuleInput } from "../types";

/** Mon..Sun — the display/iteration order every caller of `listWorkingHours` expects. */
const WEEK_ORDER: DomainDayOfWeek[] = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];

/** `"HH:mm"` -> a `@db.Time` column value (epoch-anchored UTC `Date`). */
function hhmmToTimeColumn(hhmm: string): Date {
  const [hours, minutes] = hhmm.split(":").map((part) => Number.parseInt(part, 10));
  return new Date(Date.UTC(1970, 0, 1, hours, minutes, 0, 0));
}

/** A `@db.Time` column value -> `"HH:mm"`. */
function timeColumnToHhmm(value: Date): string {
  const hours = value.getUTCHours().toString().padStart(2, "0");
  const minutes = value.getUTCMinutes().toString().padStart(2, "0");
  return `${hours}:${minutes}`;
}

function mapWorkingHoursRule(row: PrismaWorkingHoursRule): WorkingHoursRule {
  return {
    id: row.id,
    dayOfWeek: row.dayOfWeek as DomainDayOfWeek,
    isOpen: row.isOpen,
    openTime: row.openTime ? timeColumnToHhmm(row.openTime) : null,
    closeTime: row.closeTime ? timeColumnToHhmm(row.closeTime) : null,
  };
}

function sortByWeekOrder(rules: WorkingHoursRule[]): WorkingHoursRule[] {
  return [...rules].sort((a, b) => WEEK_ORDER.indexOf(a.dayOfWeek) - WEEK_ORDER.indexOf(b.dayOfWeek));
}

function mapTimeOff(row: PrismaTimeOff): TimeOff {
  return {
    id: row.id,
    startDate: row.startDate,
    endDate: row.endDate,
    reason: row.reason,
    createdAt: row.createdAt,
  };
}

export function createPrismaAvailabilityRepository(prisma: PrismaClient): AvailabilityRepository {
  /**
   * v1 has exactly one (active) Groomer (FR-2, schema.prisma's `Groomer` model comment;
   * `booking/service.ts`'s own `resolveGroomerId`/`findDefaultGroomer` makes the same
   * assumption). `claimSlot` needs a `groomerId` to check the real `(groomerId,
   * slotStart)` constraint's exact scope even though `ClaimSlotInput` doesn't carry one
   * — see the file-level architectural note above for why not.
   */
  async function resolveActiveGroomerId(): Promise<string | null> {
    const groomer = await prisma.groomer.findFirst({
      where: { active: true },
      orderBy: { createdAt: "asc" },
      select: { id: true },
    });
    return groomer?.id ?? null;
  }

  return {
    async listWorkingHours(): Promise<WorkingHoursRule[]> {
      const rows = await prisma.workingHoursRule.findMany();
      return sortByWeekOrder(rows.map(mapWorkingHoursRule));
    },

    async replaceWorkingHours(rules: WorkingHoursRuleInput[]): Promise<WorkingHoursRule[]> {
      // BR-AVAIL-7 (Flow 5, step 1) — "wholesale replace of all 7 rows," implemented as
      // one upsert per day (keyed on the `@@unique([dayOfWeek])` constraint) inside a
      // single transaction, rather than delete-all-then-recreate — this way a reader
      // hitting the table mid-transaction (outside this transaction's own isolation)
      // never sees a moment with fewer than 7 rows, and the exactly-7-rows-per-day
      // invariant documented in schema.prisma is structurally impossible to violate.
      const upserts = rules.map((rule) =>
        prisma.workingHoursRule.upsert({
          where: { dayOfWeek: rule.dayOfWeek as DayOfWeek },
          update: {
            isOpen: rule.isOpen,
            openTime: rule.isOpen && rule.openTime ? hhmmToTimeColumn(rule.openTime) : null,
            closeTime: rule.isOpen && rule.closeTime ? hhmmToTimeColumn(rule.closeTime) : null,
          },
          create: {
            dayOfWeek: rule.dayOfWeek as DayOfWeek,
            isOpen: rule.isOpen,
            openTime: rule.isOpen && rule.openTime ? hhmmToTimeColumn(rule.openTime) : null,
            closeTime: rule.isOpen && rule.closeTime ? hhmmToTimeColumn(rule.closeTime) : null,
          },
        }),
      );
      await prisma.$transaction(upserts);

      const rows = await prisma.workingHoursRule.findMany();
      return sortByWeekOrder(rows.map(mapWorkingHoursRule));
    },

    async listTimeOff(): Promise<TimeOff[]> {
      const rows = await prisma.timeOff.findMany({ orderBy: { startDate: "asc" } });
      return rows.map(mapTimeOff);
    },

    async createTimeOff(input: TimeOffCreateInput): Promise<TimeOff> {
      const row = await prisma.timeOff.create({
        data: {
          startDate: input.startDate,
          endDate: input.endDate,
          reason: input.reason ?? null,
        },
      });
      return mapTimeOff(row);
    },

    async listOccupiedRanges(windowStart: Date, windowEnd: Date, excludeAppointmentId?: string): Promise<OccupiedRange[]> {
      // Only `Booked` appointments occupy a slot — Cancelled/NoShow rows never do
      // (BR-AVAIL-11, this method's own doc comment in repository.ts), and a Completed
      // row is by definition already in the past relative to any future window this is
      // ever called with. Half-open `[slotStart, slotEnd)` overlap against
      // `[windowStart, windowEnd]`.
      const rows = await prisma.appointment.findMany({
        where: {
          status: "Booked",
          slotStart: { lt: windowEnd },
          slotEnd: { gt: windowStart },
          ...(excludeAppointmentId ? { id: { not: excludeAppointmentId } } : {}),
        },
        select: { id: true, slotStart: true, slotEnd: true },
      });
      return rows.map((row) => ({ appointmentId: row.id, start: row.slotStart, end: row.slotEnd }));
    },

    async listFutureOccupiedRanges(fromDate: Date): Promise<OccupiedRange[]> {
      const rows = await prisma.appointment.findMany({
        where: {
          status: "Booked",
          slotEnd: { gte: fromDate },
        },
        select: { id: true, slotStart: true, slotEnd: true },
      });
      return rows.map((row) => ({ appointmentId: row.id, start: row.slotStart, end: row.slotEnd }));
    },

    async claimSlot(input: ClaimSlotInput): Promise<void> {
      // See the file-level architectural note above: this is a best-effort, late
      // re-check against the live `Appointment` table (the closest this module can get
      // to the real `(groomerId, slotStart)` DB constraint without a row of its own to
      // insert) — not the final atomicity guarantee, which lives in `booking`'s
      // `createAppointment` insert-and-catch.
      const groomerId = await resolveActiveGroomerId();
      if (!groomerId) {
        // No active groomer configured — nothing could ever have claimed this slot
        // either, so there is no conflict to report. `booking`'s own
        // `resolveGroomerId`/`NoGroomerAvailableError` is the actual guard against
        // proceeding with a booking in this state; this repository method only answers
        // "is this slot taken," not "is booking possible at all."
        return;
      }

      // Deliberately not scoped by `status` — the real unique index on
      // `(groomerId, slotStart)` does not exempt Cancelled/NoShow rows either
      // (schema.prisma's own note on `Appointment`), so neither does this check.
      const conflict = await prisma.appointment.findFirst({
        where: {
          groomerId,
          slotStart: input.start,
          NOT: { id: input.appointmentId },
        },
        select: { id: true },
      });

      if (conflict) {
        throw new SlotConstraintViolationError();
      }
    },

    async forceClaimSlot(_input: ClaimSlotInput): Promise<void> {
      // SO-3 override path — nothing to persist here; see the file-level architectural
      // note above (mirrors `AvailabilityService.releaseSlot`'s already-established
      // no-op precedent). The eventual `Appointment` row (with `isOverride`/
      // `hasConflict` already computed by the caller before this method runs) is what
      // `booking`'s repository persists. `_input` is unused on purpose — kept named (not
      // omitted) so this method's signature stays self-documenting against
      // `AvailabilityRepository.forceClaimSlot`.
    },
  };
}
