// Prisma-backed implementation of `CatalogRepository` (src/modules/catalog/repository.ts).
//
// ============================================================================
// READ THIS BEFORE TOUCHING THIS FILE
// ============================================================================
// This file imports `@prisma/client`, whose TypeScript types are GENERATED by
// `npx prisma generate` from `prisma/schema.prisma`. That command cannot succeed in
// this dev container: `prisma generate`'s internal DMMF-computation step needs the
// native query-engine binary from `binaries.prisma.sh`, which this container's network
// policy blocks — confirmed even with the JS/WASM schema-engine mode already configured
// in `prisma.config.ts` (that gets the Schema Engine itself working, but the CLI's DMMF
// bootstrap for ANY command still needs the native query engine regardless).
//
// Consequences, both deliberate:
//   1. `npx tsc --noEmit`, `npx eslint .`, and `npx next build` will all fail on this
//      file today with "module '@prisma/client' has no exported member ..." — NOT
//      because the code below is wrong, but because the types it imports don't exist
//      on disk yet. This file is listed in `tsconfig.json`'s `exclude` array and in
//      `eslint.config.mjs`'s ignores for exactly this reason.
//   2. This is real, finished code — written exactly as it would be in a normal,
//      working Prisma project, against the actual field names/types/relations in
//      `prisma/schema.prisma`. It is NOT a stub. Once `prisma generate` has been run
//      somewhere with real network access (Vercel's build, or a developer's own
//      machine), this file typechecks and runs as-is — no further edits needed.
//   3. This file is NOT wired into `src/server/container.ts` yet. That composition-root
//      swap-over is intentionally deferred to whenever `prisma generate` can actually
//      run — see that file's own header comment.
// ============================================================================
//
// Mapping notes:
// - `Service.price` is `Decimal @db.Decimal(10, 2)` in the schema but a plain `number`
//   in `catalog`'s own domain type (types.ts's header comment calls this out explicitly
//   as Step 17's job). `Number(row.price)` converts Prisma's `Decimal` (decimal.js
//   instance) at the read boundary; a plain JS `number` is accepted directly by Prisma's
//   `create`/`update` `data` on the way back in — no explicit `Decimal` construction
//   needed for a value already scoped to 2 decimal places by `CreateServiceInput`'s/
//   `UpdateServiceInput`'s own validation (BR-CAT-5, validation.ts).
// - Everything else on `Service` (`name`, `durationMinutes`, `active`, `createdAt`,
//   `updatedAt`) maps 1:1 by name/type onto `catalog`'s own `Service` type.

import { PrismaClient, type Service as PrismaService } from "@prisma/client";
import type { CatalogRepository } from "../repository";
import type { CreateServiceInput, Service, UpdateServiceInput } from "../types";

function mapService(row: PrismaService): Service {
  return {
    id: row.id,
    name: row.name,
    price: Number(row.price),
    durationMinutes: row.durationMinutes,
    active: row.active,
    createdAt: row.createdAt,
    updatedAt: row.updatedAt,
  };
}

export function createPrismaCatalogRepository(prisma: PrismaClient): CatalogRepository {
  return {
    async findServiceById(serviceId: string): Promise<Service | null> {
      const row = await prisma.service.findUnique({ where: { id: serviceId } });
      return row ? mapService(row) : null;
    },

    async listActiveServices(): Promise<Service[]> {
      const rows = await prisma.service.findMany({
        where: { active: true },
        orderBy: { name: "asc" },
      });
      return rows.map(mapService);
    },

    async listAllServices(): Promise<Service[]> {
      const rows = await prisma.service.findMany({ orderBy: { name: "asc" } });
      return rows.map(mapService);
    },

    async createService(input: CreateServiceInput): Promise<Service> {
      const row = await prisma.service.create({
        data: {
          name: input.name,
          price: input.price,
          durationMinutes: input.durationMinutes,
        },
      });
      return mapService(row);
    },

    async updateService(serviceId: string, fields: UpdateServiceInput): Promise<Service> {
      const row = await prisma.service.update({
        where: { id: serviceId },
        // `undefined` fields are left untouched by Prisma's `update` — matches
        // `UpdateServiceInput`'s all-optional shape directly.
        data: {
          name: fields.name,
          price: fields.price,
          durationMinutes: fields.durationMinutes,
        },
      });
      return mapService(row);
    },

    async setServiceActive(serviceId: string, active: boolean): Promise<Service> {
      const row = await prisma.service.update({
        where: { id: serviceId },
        data: { active },
      });
      return mapService(row);
    },
  };
}
